#!/usr/bin/python

f = open('myworkfile','w')

stringName = "./sumrange"

seq = [stringName + " " + str((x*100)-99) + " " + str(x*100) + " " + str(x) + "\n" for x in range(1,161)]

f.writelines(seq)
    
f.close()
