#!/usr/bin/python
import sys
import fileinput
import random
import time

n = sys.argv[1]
m = sys.argv[2]
k = sys.argv[3]

sumFinal = sum(range(int(n),int(m)+1))

q = random.randint(1,5);
time.sleep(q)


fname = 'out.' + str(k)
f = open(fname,'w')
f.write(str(sumFinal))
f.close()

